module Scenes.Transition2.LayerSettings exposing
    ( LayerDataType(..)
    , LayerT
    )

{-| This module is generated by Messenger, don't modify this.

@docs LayerDataType
@docs LayerT

-}

import Lib.Layer.Base exposing (Layer)
import Scenes.Transition2.Background.Export as Background
import Scenes.Transition2.LayerBase exposing (CommonData)
import Scenes.Transition2.Room.Export as Room


{-| LayerDataType
-}
type LayerDataType
    = BackgroundData Background.Data
    | RoomData Room.Data
    | NullLayerData


{-| LayerT
-}
type alias LayerT =
    Layer LayerDataType CommonData
