module Scenes.Level3.LayerSettings exposing
    ( LayerDataType(..)
    , LayerT
    )

{-| This module is generated by Messenger, don't modify this.

@docs LayerDataType
@docs LayerT

-}

import Lib.Layer.Base exposing (Layer)
import Scenes.Level3.Background.Export as Background
import Scenes.Level3.GameStuff.Export as GameStuff
import Scenes.Level3.LayerBase exposing (CommonData)


{-| LayerDataType
-}
type LayerDataType
    = BackgroundData Background.Data
    | GameStuffData GameStuff.Data
    | NullLayerData


{-| LayerT
-}
type alias LayerT =
    Layer LayerDataType CommonData
