module Scenes.Rules.Common exposing (Model, nullModel, initModel)

{-| Common module

This module is generated by Messenger, don't modify this.

@docs Model, nullModel, initModel

-}

import Lib.Env.Env exposing (Env, addCommonData)
import Lib.Scene.Base exposing (LayerPacker, SceneInitData(..))
import Scenes.Rules.LayerBase exposing (CommonData, nullCommonData)
import Scenes.Rules.LayerSettings exposing (LayerT)
import Scenes.Rules.Rulespage.Export as Rulespage
import Scenes.Rules.Rulespage.Global as RulespageG
import Scenes.Rules.SceneInit exposing (initCommonData, nullRulesInit)


{-| Model
-}
type alias Model =
    LayerPacker CommonData LayerT


{-| nullModel
-}
nullModel : Model
nullModel =
    { commonData = nullCommonData
    , layers = []
    }


{-| Initialize the model
-}
initModel : Env -> SceneInitData -> Model
initModel env init =
    let
        layerInitData =
            case init of
                RulesInitData x ->
                    x

                _ ->
                    nullRulesInit
    in
    { commonData = initCommonData env layerInitData
    , layers =
        [ RulespageG.getLayerT <| Rulespage.initLayer (addCommonData nullCommonData env) layerInitData
        ]
    }
