module Scenes.Rules.LayerSettings exposing
    ( LayerDataType(..)
    , LayerT
    )

{-| This module is generated by Messenger, don't modify this.

@docs LayerDataType
@docs LayerT

-}

import Lib.Layer.Base exposing (Layer)
import Scenes.Rules.LayerBase exposing (CommonData)
import Scenes.Rules.Rulespage.Export as Rulespage


{-| LayerDataType
-}
type LayerDataType
    = RulespageData Rulespage.Data
    | NullLayerData


{-| LayerT
-}
type alias LayerT =
    Layer LayerDataType CommonData
