module Scenes.Logo.Common exposing (Model, nullModel, initModel)

{-| Common module

This module is generated by Messenger, don't modify this.

@docs Model, nullModel, initModel

-}

import Lib.Env.Env exposing (Env, addCommonData)
import Lib.Scene.Base exposing (LayerPacker, SceneInitData(..))
import Scenes.Logo.Background.Export as Background
import Scenes.Logo.Background.Global as BackgroundG
import Scenes.Logo.LayerBase exposing (CommonData, nullCommonData)
import Scenes.Logo.LayerSettings exposing (LayerT)
import Scenes.Logo.SceneInit exposing (initCommonData, nullLogoInit)


{-| Model
-}
type alias Model =
    LayerPacker CommonData LayerT


{-| nullModel
-}
nullModel : Model
nullModel =
    { commonData = nullCommonData
    , layers = []
    }


{-| Initialize the model
-}
initModel : Env -> SceneInitData -> Model
initModel env init =
    let
        layerInitData =
            case init of
                LogoInitData x ->
                    x

                _ ->
                    nullLogoInit
    in
    { commonData = initCommonData env layerInitData
    , layers =
        [ BackgroundG.getLayerT <| Background.initLayer (addCommonData nullCommonData env) layerInitData
        ]
    }
