module Scenes.Logo.LayerSettings exposing
    ( LayerDataType(..)
    , LayerT
    )

{-| This module is generated by Messenger, don't modify this.

@docs LayerDataType
@docs LayerT

-}

import Lib.Layer.Base exposing (Layer)
import Scenes.Logo.Background.Export as Background
import Scenes.Logo.LayerBase exposing (CommonData)


{-| LayerDataType
-}
type LayerDataType
    = BackgroundData Background.Data
    | NullLayerData


{-| LayerT
-}
type alias LayerT =
    Layer LayerDataType CommonData
