module Scenes.Transition1.LayerSettings exposing
    ( LayerDataType(..)
    , LayerT
    )

{-| This module is generated by Messenger, don't modify this.

@docs LayerDataType
@docs LayerT

-}

import Lib.Layer.Base exposing (Layer)
import Scenes.Transition1.Background.Export as Background
import Scenes.Transition1.LayerBase exposing (CommonData)
import Scenes.Transition1.Room.Export as Room


{-| LayerDataType
-}
type LayerDataType
    = RoomData Room.Data
    | BackgroundData Background.Data
    | NullLayerData


{-| LayerT
-}
type alias LayerT =
    Layer LayerDataType CommonData
