module Scenes.Home.Common exposing (Model, nullModel, initModel)

{-| Common module

This module is generated by Messenger, don't modify this.

@docs Model, nullModel, initModel

-}

import Lib.Env.Env exposing (Env, addCommonData)
import Lib.Scene.Base exposing (LayerPacker, SceneInitData(..))
import Scenes.Home.Background.Export as Background
import Scenes.Home.Background.Global as BackgroundG
import Scenes.Home.LayerBase exposing (CommonData, nullCommonData)
import Scenes.Home.LayerSettings exposing (LayerT)
import Scenes.Home.SceneInit exposing (initCommonData, nullHomeInit)
import Scenes.Home.UI.Export as UI
import Scenes.Home.UI.Global as UIG


{-| Model
-}
type alias Model =
    LayerPacker CommonData LayerT


{-| nullModel
-}
nullModel : Model
nullModel =
    { commonData = nullCommonData
    , layers = []
    }


{-| Initialize the model
-}
initModel : Env -> SceneInitData -> Model
initModel env init =
    let
        layerInitData =
            case init of
                HomeInitData x ->
                    x

                _ ->
                    nullHomeInit
    in
    { commonData = initCommonData env layerInitData
    , layers =
        [ BackgroundG.getLayerT <| Background.initLayer (addCommonData nullCommonData env) layerInitData
        , UIG.getLayerT <| UI.initLayer (addCommonData nullCommonData env) layerInitData
        ]
    }
