module Scenes.Home.LayerSettings exposing
    ( LayerDataType(..)
    , LayerT
    )

{-| This module is generated by Messenger, don't modify this.

@docs LayerDataType
@docs LayerT

-}

import Lib.Layer.Base exposing (Layer)
import Scenes.Home.Background.Export as Background
import Scenes.Home.LayerBase exposing (CommonData)
import Scenes.Home.UI.Export as UI


{-| LayerDataType
-}
type LayerDataType
    = BackgroundData Background.Data
    | UIData UI.Data
    | NullLayerData


{-| LayerT
-}
type alias LayerT =
    Layer LayerDataType CommonData
