module Scenes.AllScenes exposing (allScenes)

{-| This module is generated by Messenger, don't modify this.

This module records all the scenes.

@docs allScenes

-}

import Scenes.Home.Export as Home
import Scenes.Home.Global as HomeG
import Scenes.Level1.Export as Level1
import Scenes.Level1.Global as Level1G
import Scenes.Level2.Export as Level2
import Scenes.Level2.Global as Level2G
import Scenes.Level3.Export as Level3
import Scenes.Level3.Global as Level3G
import Scenes.Logo.Export as Logo
import Scenes.Logo.Global as LogoG
import Scenes.LogoEnd.Export as LogoEnd
import Scenes.LogoEnd.Global as LogoEndG
import Scenes.Rules.Export as Rules
import Scenes.Rules.Global as RulesG
import Scenes.SceneSettings exposing (SceneT)
import Scenes.Story.Export as Story
import Scenes.Story.Global as StoryG
import Scenes.Transition1.Export as Transition1
import Scenes.Transition1.Global as Transition1G
import Scenes.Transition2.Export as Transition2
import Scenes.Transition2.Global as Transition2G


{-| allScenes
Add all the scenes here
-}
allScenes : List ( String, SceneT )
allScenes =
    [ ( "Story", StoryG.sceneToST Story.scene )
    , ( "Home", HomeG.sceneToST Home.scene )
    , ( "Rules", RulesG.sceneToST Rules.scene )
    , ( "Logo", LogoG.sceneToST Logo.scene )
    , ( "LogoEnd", LogoEndG.sceneToST LogoEnd.scene )
    , ( "Level1", Level1G.sceneToST Level1.scene )
    , ( "Level2", Level2G.sceneToST Level2.scene )
    , ( "Transition1", Transition1G.sceneToST Transition1.scene )
    , ( "Transition2", Transition2G.sceneToST Transition2.scene )
    , ( "Level3", Level3G.sceneToST Level3.scene )
    ]
