module Scenes.SceneSettings exposing
    ( SceneDataTypes(..)
    , SceneT
    , nullSceneT
    )

{-| This module is generated by Messenger, don't modify this.

@docs SceneDataTypes
@docs SceneT
@docs nullSceneT

-}

import Canvas exposing (empty)
import Lib.Scene.Base exposing (Scene)
import Scenes.Home.Export as Home
import Scenes.Level1.Export as Level1
import Scenes.Level2.Export as Level2
import Scenes.Level3.Export as Level3
import Scenes.Logo.Export as Logo
import Scenes.LogoEnd.Export as LogoEnd
import Scenes.Rules.Export as Rules
import Scenes.Story.Export as Story
import Scenes.Transition1.Export as Transition1
import Scenes.Transition2.Export as Transition2



--- Set Scenes


{-| SceneDataTypes

All the scene data types should be listed here.

-}
type SceneDataTypes
    = StoryDataT Story.Data
    | HomeDataT Home.Data
    | RulesDataT Rules.Data
    | LogoDataT Logo.Data
    | LogoEndDataT LogoEnd.Data
    | Level1DataT Level1.Data
    | Level2DataT Level2.Data
    | Transition1DataT Transition1.Data
    | Transition2DataT Transition2.Data
    | Level3DataT Level3.Data
    | NullSceneData


{-| SceneT

SceneT is a Scene with datatypes.

-}
type alias SceneT =
    Scene SceneDataTypes


{-| nullSceneT
-}
nullSceneT : SceneT
nullSceneT =
    { init = \_ _ -> NullSceneData
    , update = \env m -> ( m, [], env )
    , view = \_ _ -> empty
    }
