module Scenes.Level1.Common exposing (Model, nullModel, initModel)

{-| Common module

This module is generated by Messenger, don't modify this.

@docs Model, nullModel, initModel

-}

import Lib.Env.Env exposing (Env, addCommonData)
import Lib.Scene.Base exposing (LayerPacker, SceneInitData(..))
import Scenes.Level1.Background.Export as Background
import Scenes.Level1.Background.Global as BackgroundG
import Scenes.Level1.GameStuff.Export as GameStuff
import Scenes.Level1.GameStuff.Global as GameStuffG
import Scenes.Level1.LayerBase exposing (CommonData, nullCommonData)
import Scenes.Level1.LayerSettings exposing (LayerT)
import Scenes.Level1.SceneInit exposing (initCommonData, nullLevel1Init)


{-| Model
-}
type alias Model =
    LayerPacker CommonData LayerT


{-| nullModel
-}
nullModel : Model
nullModel =
    { commonData = nullCommonData
    , layers = []
    }


{-| Initialize the model
-}
initModel : Env -> SceneInitData -> Model
initModel env init =
    let
        layerInitData =
            case init of
                Level1InitData x ->
                    x

                _ ->
                    nullLevel1Init
    in
    { commonData = initCommonData env layerInitData
    , layers =
        [ BackgroundG.getLayerT <| Background.initLayer (addCommonData nullCommonData env) layerInitData
        , GameStuffG.getLayerT <| GameStuff.initLayer (addCommonData nullCommonData env) layerInitData
        ]
    }
